#!/bin/bash
set -e # exit with nonzero exit code if anything fails
base=`basename $TRAVIS_REPO_SLUG`
# inside this git repo we'll pretend to be a new user
git config --global user.name "Travis CI"
git config --global user.email "travis@nomail"
# clone the existing github url to some directory
git clone https://github.com/NSLS-II/NSLS-II.github.io /tmp/docs
cp -rv build/html/* /tmp/$base
cd /tmp/$base
git add -A
git commit -m "Autogenerated pages `date`"
# Force push from the current repo's master branch to the remote
# repo's gh-pages branch. (All previous history on the gh-pages branch
# will be lost, since we are overwriting it.) We redirect any output to
# /dev/null to hide any sensitive credential data that might otherwise be exposed.
git push "https://${GH_TOKEN}@${GH_REF}" master > /dev/null 2>&1
